version: "3.7"

services:
  build-3d-printer-monitor:
    image: 3d-printer-monitor
    build:
      context: .
      dockerfile: Dockerfile

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
    depends_on:
      - zookeeper
  akhq:
    container_name: akhq
    image: tchiotludo/akhq:latest
    networks:
      - kafka-net
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-dev:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka

  carriage-speed-simulator:
    image: 3d-printer-monitor
    command: sbt "sensor-simulator / run carriage-speed"
    networks:
      - kafka-net
    depends_on:
      - kafka
  bed-temp-simulator:
    image: 3d-printer-monitor
    command: sbt "sensor-simulator / run bed-temp"
    networks:
      - kafka-net
    depends_on:
      - kafka
  data-consumer:
    image: 3d-printer-monitor
    command: sbt "sensor-simulator / run bed-temp,carriage-speed"
    networks:
      - kafka-net
    depends_on:
      - carriage-speed-simulator
      - bed-temp-simulator

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
