version: "2"

services:
  build-sensor-simulator:
    build:
      context: ./sensor-simulator
      dockerfile: sensor-simulator.dockerfile
    image: sensor-simulator
  build-data-consumer:
    build:
      context: ./data-consumer
      dockerfile: data-consumer.dockerfile
    image: data-consumer

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
    depends_on:
      - zookeeper
  akhq:
    container_name: akhq
    image: tchiotludo/akhq:latest
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-dev:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka

  carriage-speed-simulator:
    image: sensor-simulator
    environment:
      - PROJECT=sensor-simulator
      - SIMULATOR_TYPE=carriage-speed
#    command: ["./app.sh", "carriageSpeed"]
    depends_on:
      - kafka
  bed-temp-simulator:
    image: sensor-simulator
    environment:
      - PROJECT=sensor-simulator
      - SIMULATOR_TYPE=bed-temperature
#    command: ["./app.sh", "bedTemp"]
    depends_on:
      - kafka
  data-consumer:
    image: data-consumer
    environment:
      - PROJECT=data-consumer
      - SIMULATOR_TYPE=carriage-speed,bed-temperature
#    command: sbt run
    depends_on:
      - carriage-speed-simulator
      - bed-temp-simulator

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
