version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
    depends_on:
      - zookeeper
  akhq:
    container_name: akhq
    image: tchiotludo/akhq:latest
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-dev:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka
#  carriage-speed-simulator:
#    build: ./sensor-simulator
#    command: ["./app.sh", "carriageSpeed"]
#    tty: true
#    depends_on:
#      - kafka
#  bed-temp-simulator:
#    build: ./sensor-simulator
#    command: ["./app.sh", "bedTemp"]
#    tty: true
#    depends_on:
#      - kafka
#  consumer:
#    build: ./consumer
#    command: sbt run
#    tty: true
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
    
    # environment:
    #   KAFKA_BROKER_ID: 1
    #   KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #   KAFKA_JMX_PORT: 9101
    #   KAFKA_JMX_HOSTNAME: localhost
